# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            gelvinwhite
tagline:          'A Jekyll theme'
description:      'musical coding. generative music. algorithmic composition'
url:              https://www.gelvinwhite.com/
baseurl:          /

author:
  name:           'G. Elvin White'
  url:            https://www.gelvinwhite.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           test

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
