# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            gelvinwhite
tagline:          'generative music and code'
description:      'Description here'
url:              https://www.gelvinwhite.com
baseurl:          /

author:
  name:           'gelvinwhite'
  url:             https://www.gelvinwhite.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
