# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            gelvinwhite
tagline:          'musical coding. generative music. algorithmic composition'
description:      'musical coding. generative music. algorithmic composition'
url:              gelvinwhite.com
baseurl:          /

author:
  name:           'G. Elvin White'
  url:            gelvinwhite.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           test

plugins:
  -  jekyll-sitemap

whitelist:
  - jekyll-sitemap
